// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_office_booking/test/unit_test/user_api_test.dart.
// Do not manually edit this file.

import 'package:dio/dio.dart' as _i2;
import 'package:flutter_office_booking/services/api/user_api.dart' as _i3;
import 'package:image_picker/image_picker.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDio_0 extends _i1.Fake implements _i2.Dio {}

/// A class which mocks [UserApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserApi extends _i1.Mock implements _i3.UserApi {
  MockUserApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio_0())
          as _i2.Dio);
  @override
  dynamic postProfilImage(dynamic id, dynamic token, _i4.XFile? image) => super
      .noSuchMethod(Invocation.method(#postProfilImage, [id, token, image]));
}
